name: GitHub Pages Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE.md

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Build & Deploy

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

      - name: Bypass Jekyll processing
        run: touch "dist/.nojekyll"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: dist
